name: Build and Deploy

on:
  push: 
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing tabletopcast.de server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: tabletopcast.de
        username: dominik
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd tabletop_cast
          git pull origin main
          git status