name: Build and Deploy

on:
  push: 
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Build and run new release
      uses: appleboy/ssh-action@master
      with:
        host: tabletopcast.de
        username: dominik
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          export ASDF_DIR=~/.asdf/shims
          cd tabletop_cast
          git pull origin main
          $ASDF_DIR/mix deps.get --only prod
          MIX_ENV=prod $ASDF_DIR/mix compile
          MIX_ENV=prod $ASDF_DIR/mix ecto.migrate
          $ASDF_DIR/npm run deploy --prefix ./assets
          $ASDF_DIR/mix phx.digest
          MIX_ENV=prod $ASDF_DIR/mix release --overwrite
          _build/prod/rel/tabletop_cast/bin/tabletop_cast stop
          _build/prod/rel/tabletop_cast/bin/tabletop_cast daemon
